//
// Generated file, do not edit! Created by opp_msgtool 6.1 from WSNPacket.msg.
//

#ifndef __WSNPACKET_M_H
#define __WSNPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class WSNPacket;
/**
 * Class generated from <tt>WSNPacket.msg:2</tt> by opp_msgtool.
 * <pre>
 * message WSNPacket
 * {
 *     int srcId = -1;
 *     int lastHopId = -1;
 *     int finalDstId = -1;
 *     int seq = 0;
 *     int hopCount = 0;
 *     int ttl = 10;
 *     simtime_t createdAt = 0;
 * 
 *     bool isCoded = false;
 *     int srcId2 = -1;
 *     int seq2 = -1;
 * }
 * </pre>
 */
class WSNPacket : public ::omnetpp::cMessage
{
  protected:
    int srcId = -1;
    int lastHopId = -1;
    int finalDstId = -1;
    int seq = 0;
    int hopCount = 0;
    int ttl = 10;
    omnetpp::simtime_t createdAt = 0;
    bool isCoded_ = false;
    int srcId2 = -1;
    int seq2 = -1;

  private:
    void copy(const WSNPacket& other);

  protected:
    bool operator==(const WSNPacket&) = delete;

  public:
    WSNPacket(const char *name=nullptr, short kind=0);
    WSNPacket(const WSNPacket& other);
    virtual ~WSNPacket();
    WSNPacket& operator=(const WSNPacket& other);
    virtual WSNPacket *dup() const override {return new WSNPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getLastHopId() const;
    virtual void setLastHopId(int lastHopId);

    virtual int getFinalDstId() const;
    virtual void setFinalDstId(int finalDstId);

    virtual int getSeq() const;
    virtual void setSeq(int seq);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);

    virtual omnetpp::simtime_t getCreatedAt() const;
    virtual void setCreatedAt(omnetpp::simtime_t createdAt);

    virtual bool isCoded() const;
    virtual void setIsCoded(bool isCoded);

    virtual int getSrcId2() const;
    virtual void setSrcId2(int srcId2);

    virtual int getSeq2() const;
    virtual void setSeq2(int seq2);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WSNPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WSNPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline WSNPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<WSNPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __WSNPACKET_M_H

